### ISSUE TITLE
tla-plus org name is misleading

### ISSUE THREAD

**Issue by lemmy** [jameshfisher/tlaplus#1]
Hi James,

the tla-plus org name is misleading. It gives the false impression as if this is the "official" repository for the TLA+ project. Can you please alter the org name so that it becomes clear that this is your personal fork of TLA+.

Btw. your patches are more than welcomed at the (official home)[http://tlaplus.codeplex.com/] of the TLA+ project.

Thanks
Markus Kuppe

**Comment by jameshfisher** [comment]
Hi Markus,

Sorry for that; you're totally right. I'd forgotten I had the repository at that location. I've moved it to jameshfisher/tlaplus.

Best wishes,

James

**Comment by lemmy** [comment]
Thanks James.

Btw. you should get your master branch back in sync with the CodePlex repository. At lot has changed since November.
